---
- name: set hostname
  hostname:
    name: "{{ hostname }}"

- name: disable selinux
  shell: "setenforce 0 && sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config"
  become: true
